language: r
cache: packages

r:
#  - oldrel
  - release
#  - devel

notifications:
  email:
    recipients:
      - dperepolkin@gmail.com
    on_success: change
    on_failure: change

git:
  depth: false

# or branches:
#        except:
branches:
  only:
    - master

# this is a comment
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
  deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
